server {
    listen 80;
    server_name admin.karunavillas.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name admin.karunavillas.com;

    root /var/www/admin.karunavillas.com/dist;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/admin.karunavillas.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.karunavillas.com/privkey.pem;

    include /etc/nginx/snippets/admin-cache-policy.locations.conf;
}
